### ISSUE TITLE
Mention loadOutDirsFromCheck in FAQ for rust-analyzer completion

### ISSUE THREAD

**Issue by ghost** [godot-rust/gdnative-book#10]
Some users seem to have trouble with auto-completion. Setting `"rust-analyzer.cargo.loadOutDirsFromCheck": true` might resolve the problem as mentioned in many rust-analyzer issues.

**Comment by extrawurst** [comment]
I will tackle this if it's ok

**Comment by ghost** [comment]
@extrawurst That would be great!
