### ISSUE TITLE
can't install gdnative 0.9

### ISSUE THREAD

**Issue by Septias** [godot-rust/gdnative-book#12]
There is instruction on the hello-world page (https://godot-rust.github.io/book/getting-started/hello-world.html) which states that gdnative should be added with version 0.9. This results in this error: 
```
failed to select a version for the requirement gdnative = "^0.9"
  candidate versions found which didn't match: 0.8.1, 0.8.0, 0.7.0, ...
```
I just tried it with gdnative 8.0 and it solved the issue, but I suggest tips for other users to make it work.

**Comment by ghost** [comment]
That's because 0.9 isn't actually released yet -- this user guide is intended to be used with version 0.9 *when it get released*. For now, you may use the pre-release version `0.9.0-preview.0` with this guide.

**Comment by Septias** [comment]
Okay, thank you 👍
