### ISSUE TITLE
godot-rust project template

### ISSUE THREAD

**Issue by macalimlim** [godot-rust/gdnative-book#14]
Hi :smile: I apologize in advance if Im posting it here since this is not an issue. I recently created a godot-rust project template. It just basically bootstraps your godot-rust project directory. You could find the the project [here](https://github.com/macalimlim/godot-rust-template) and check out the [wiki](https://github.com/macalimlim/godot-rust-template/wiki) on how to use it. I would also like to add this on the book and maybe somebody might find this useful...

**Comment by ghost** [comment]
Hello! We do have a [Third-party resources](https://github.com/godot-rust/godot-rust#third-party-resources) section in the README of the main repo, but the user guide is intended to contain only first-party content. From our past experience, third-party resources usually go unmaintained after initial creation. Project templates, especially, can cause significant confusion for users and maintainers if they're out of date. As such, we would only consider including one if we can keep it up-to-date in case the original maintainer is no longer available.

Would you consider contributing the template to the godot-rust organization, so it can be maintained along with the main repo? You will keep push access to the repo if you do so, but we do expect committers to also go through the PR process around here.

If you wouldn't, you may still make a PR to add it to README in the main repo, instead.

**Comment by macalimlim** [comment]
Sure, I would love to contribute the template to the godot-rust organization. Please advise for the next steps, thanks :+1:

**Comment by ghost** [comment]
Great! I'll create an invite for you to join the org, which will go to the email address used for your GitHub account. Once you accept it, you should be able to transfer the repo to the organization from Repo Settings -> (bottom) Danger Zone -> Transfer.

**Comment by macalimlim** [comment]
Thankyou :smile:
