### ISSUE TITLE
Unable to finish Setup of hello world

### ISSUE THREAD

**Issue by nickzelei** [godot-rust/gdnative-book#31]
Hey there, I'm running into an error when running `make run` on a clean setup of the initial hello world setup.
https://godot-rust.github.io/book/getting-started/setup.html#usage
```
$ cargo generate --git https://github.com/godot-rust/godot-rust-template --name my-awesome-game
$ cd my-awesome-game
$ make run
```
```
➜  my-awesome-game git:(master) ✗ make run
make build-x86_64-apple-darwin-debug
cargo build --target x86_64-apple-darwin
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
mv -b ./target/x86_64-apple-darwin/debug/*.dylib ./lib/x86_64-apple-darwin
mv: illegal option -- b
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
make[1]: *** [build-x86_64-apple-darwin-debug] Error 64
make: *** [run] Error 2
```
It appears that the macOS `mv` does not support the `-b` command. Seeing as this guide was written for MacOS, I'm surprised that this is here. Curious what the workaround is for this?

Computer information:
```
                   'c.          nickzelei@Nick-Zeleis-MacBook-Pro.local
                 ,xNMM.          ---------------------------------------
               .OMMMMo           OS: macOS 11.5.1 20G80 x86_64
               OMMM0,            Host: MacBookPro15,2
     .;loddo:' loolloddol;.      Kernel: 20.6.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 17 days, 3 hours, 45 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 80 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1440x900@2x
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Rectangle
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    Terminal: iTerm2
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal Font: Monaco 12
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Intel i5-8279U (8) @ 2.40GHz
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Intel Iris Plus Graphics 655
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 10532MiB / 16384MiB
       .cooc,.    .,coo:.


```

**Comment by jacobsky** [comment]
Hi @nickzelei,

The template's repository might be a better place for this issue as it doesn't seem like it's necessarily an issue related to the book instructions, but rather an issue with the makefile itself. I'm not sure how many contributors actually have tried to run this on MacOS.

After a quick peek, it seems like the template is assuming that cargo make is being run with a linux-based shell where `mv -b` refers to the "move file" and "-b" indicates that it should backup the file. If you know the correct command for this on mac and modify the Makefile accordingly, you should be able to get it to work.

As another workaround, you can always run `cargo build` and copy the output library to the correct directory by hand.

**Comment by nickzelei** [comment]
Whoops, my bad. I didn't realize this was the wrong repo. Thanks for the tips!
