### ISSUE TITLE
Missing examples for manually registering properties and methods

### ISSUE THREAD

**Issue by jacobsky** [godot-rust/gdnative-book#38]
Currently, the getting started guide does a great job at outlining a lot of the ways we can use the functionality of the code, but there aren't any solid examples for how to manually register functions or (more importantly) properties in the inspector.

This can lead to some unexpected behavior, especially when working with enums or custom filepaths (not to be confused with `NodePath` which works perfectly fine).

This should also demonstrate how to register enums with Godot since it currently registers Enums as a dictionary instead of a u32 as I initially expected.

Specific topics I will include:
- [ ] using the class builder to register properties
- [ ] Implementing `Export`, `ToVariant` and `FromVariant` for an enum type
- [ ] Implementing `Export`, `ToVariant` and `FromVariant` for a Native class type

This will also help me not forget how to do this in the future 😆

**Comment by Bromeon** [comment]
Great idea! 🙂

**Comment by jacobsky** [comment]
Oh right, I forgot about this one, I have a partial guide that I'm trying to keep relatively implementation agnostic. I'll try to wrap up a first draft and then open a draft PR.

**Comment by jacobsky** [comment]
This should be closed as of #51
