### ISSUE TITLE
[FAQ Entry] How to implement polymorphic functions?

### ISSUE THREAD

**Issue by bluenote10** [godot-rust/gdnative-book#54]
This would be a possible candidate as an FAQ entry: _How to implement polymorphic functions?_

For instance, the goal is to implement a free-floating helper function that can operate on any `Control` like:

```rust
pub fn set_anchor_full_rect_non_polymorphic(control: &Ref<Control, Unique>) {
    control.set_anchor(GlobalConstants::MARGIN_RIGHT, 0.0, false, true);
    control.set_anchor(GlobalConstants::MARGIN_BOTTOM, 0.0, false, true);
    control.set_anchor(GlobalConstants::MARGIN_RIGHT, 1.0, false, true);
    control.set_anchor(GlobalConstants::MARGIN_BOTTOM, 1.0, false, true);
}
```

Due to the explicit use of `Control` this isn't polymorphic though.

I assume this can be solved using `SubClass`. My naive attempt

```rust
pub fn set_anchor_full_rect<T>(control: &Ref<T, Unique>)
where
    T: GodotObject<RefKind = ManuallyManaged> + SubClass<Control>,
{
    control.set_anchor(GlobalConstants::MARGIN_RIGHT, 0.0, false, true);
    control.set_anchor(GlobalConstants::MARGIN_BOTTOM, 0.0, false, true);
    control.set_anchor(GlobalConstants::MARGIN_RIGHT, 1.0, false, true);
    control.set_anchor(GlobalConstants::MARGIN_BOTTOM, 1.0, false, true);
}
```

doesn't quite work though (no method named `set_anchor` found for reference `&godot::Ref<T, godot::prelude::Unique>`), and probably using `Unique` isn't ideal in terms of re-usability.

**Comment by jacobsky** [comment]
@bluenote10 Thanks for the idea. I think this would be a good candidate for the book as it's a solid usecase.

Just to clarify, the question is essentially "How do to access to the subclass functions?", correct?

For example: From a `Ref<Control>` how do you access a the `CanvasItem` functions?

In the example above, you should be able to use the subclass, but you would need to add a `let control = control.cast::<Control>` to explicitly [cast the type](https://docs.rs/gdnative/0.9.3/gdnative/struct.TRef.html#method.cast) into the type that uses it.

**Comment by bluenote10** [comment]
> Just to clarify, the question is essentially "How do to access to the subclass functions?", correct?

What I meant is: How can I pass in any class that is a subclass of `Container`?

In this example `set_anchor` is a method defined on `Container`. Now it would be nice to pass in all the various [classes that derive from `Container`](https://docs.godotengine.org/en/stable/classes/class_container.html) like `CenterContainer`, `MarginContainer`, ... without having to manually upcast them to `Container` at call site.

**Comment by Bromeon** [comment]
If you work with `TRef`, let's say you have this:
```rs
fn your_code() {
	let concrete: Ref<PanelContainer> = PanelContainer::new().into_shared();
	let concrete: TRef<PanelContainer> = unsafe { concrete.assume_safe() };
	takes_base_class(concrete);
}
```

Then either you use the `SubClass` bound, which allows you to call `upcast()`.
Read this as "accept anything that is a subclass of `Container`" -- you still need to upcast to get the actual `Container`.
```rs
fn takes_base_class<T>(control: TRef<'_, T>)
	where T: GodotObject + SubClass<Container>
{
	let base = control.upcast();
	base.set_anchor(GlobalConstants::MARGIN_RIGHT, 1.0, false, true);
}
```

Alternatively, you can also work with the `Deref` trait, this is a bit less explicit and using some internals.
Read this as "accept anything that dereferences to `Container`".
```rs
fn takes_base_class<T>(control: TRef<'_, T>)
	where T: GodotObject + Deref<Target=Container>
{
	control.set_anchor(GlobalConstants::MARGIN_RIGHT, 1.0, false, true);
}
```

**Comment by chitoyuu** [comment]
> Alternatively, you can also work with the `Deref` trait, this is a bit less explicit and using some internals.
> Read this as "accept anything that dereferences to `Container`".

This won't work for sub-classes at two or more levels down, though, while `SubClass` is implemented for all descendants whichever layer they're on.

**Comment by jacobsky** [comment]
> 
> 
> > Alternatively, you can also work with the `Deref` trait, this is a bit less explicit and using some internals.
> > Read this as "accept anything that dereferences to `Container`".
> 
> This won't work for sub-classes at two or more levels down, though, while `SubClass` is implemented for all descendants whichever layer they're on.

I'm not super familiar with the subclass trait, but if I understand correctly, this is because we don't or can'T implement `SubClass` recursively, correct?

For now, I think it would be worth having this addressed in the FAQ and then we can note the limitation for the time being.

**Comment by chitoyuu** [comment]
> I'm not super familiar with the subclass trait, but if I understand correctly, this is because we don't or can'T implement `SubClass` recursively, correct?

Yes. I believe a recursive implementation would have to contain an unconstrained type variable. Even if it was possible to write, it would still conflict with the blanket implementation of `SubClass<T>` for `T` without full specialization.

**Comment by Bromeon** [comment]
> This won't work for sub-classes at two or more levels down, though, while `SubClass` is implemented for all descendants whichever layer they're on.

Thanks, this is a very good point, and should become part of the book as well. We should probably discourage people from using `Deref` explicitly.

In addition to a dedicated FAQ entry for upcasting, we might also want to add the following description to [_Data representations > Object and class_](https://godot-rust.github.io/book/gdnative-overview/data-representations.html#object-and-class):

> Since Rust does not support inheritance, an inheritance relation is expressed via the `SubClass` trait. The bound `Derived : SubClass<Base>` means that the type `Derived` inherits `Base`. This is also true for indirect inheritance across multiple levels. See [this FAQ entry] for detailed explanation.

**Comment by bluenote10** [comment]
Thanks for the clarification! I think I begin to see what I missed about `SubClass`. Here is an attempt at explaining it for the FAQ:

_Note that `SubClass` is only a marker trait that models the inheritance relationship of Godot classes, and doesn't perform any conversion by itself. For instance, `x: Ref<T>` or `x: TRef<'_, T>` satisfying `T: GodotObject + SubClass<Container>` doesn't mean that `x` can be used as a `Container` directly. Rather, it ensures that e.g. `x.upcast::<Container>()` is guaranteed to work, because `T` is a subclass of `Container`. Therefore, it is a common pattern to use `SubClass` constraints in combination with `.upcast()` to convert to the base class, and actually use `x` as such._

**Comment by jacobsky** [comment]
@bluenote10 Thank you for all the help with looking into this. Do you want to work on a PR or would you like this issue to remain open as a work-item for myself to create this entry?

**Comment by bluenote10** [comment]
Entry is added, so I guess this can be closed.
