### ISSUE TITLE
Contributing link in README broken

### ISSUE THREAD

**Issue by JasmineLowen** [godot-rust/gdnative-book#93]
Description in title. The link is broken. Also the file is missing even if the link wasn't broken.

**Comment by Bromeon** [comment]
Which link exactly?

"main repo" correctly redirects https://github.com/godot-rust/godot-rust -> https://github.com/godot-rust/gdnative, so it's at most "not a direct link", but not broken. In there, you'll find a `CONTRIBUTING.md` file.

**Comment by JasmineLowen** [comment]
Sorry. I meant [this link](https://github.com/godot-rust/book/blob/master/README.md?plain=1#L25). For me, it doesn't appear to be a link on the repos rendered landing-README-page.

*edit:

Also, the link there:

https://github.com/godot-rust/godot-rust/blob/book/CONTRIBUTING.md

doesn't point to a valid file.
