### ISSUE TITLE
Android NDK version >= 23 requires nightly toolchain

### ISSUE THREAD

**Issue by necrashter** [godot-rust/gdnative-book#95]
`libgcc` was removed in Android NDK version `r23-beta3` and Rust was updated accordingly (see [this issue](https://github.com/rust-lang/rust/pull/85806)). However, this change does not seem to be available in stable Rust yet (2023-03-04). This is should be mentioned in [exporting for Android](https://godot-rust.github.io/book/gdnative/export/android.html) section.

I will make a PR for this but I'm not sure where we should mention it. My idea is to add a "Troubleshooting" section similar to ["Errors you might encounter"](https://godot-rust.github.io/book/gdnative/export/html5.html#errors-you-might-encounter) in HTML5 export page. But I think it should be included at the start as well since users start following instructions before reading the troubleshooting.

**Comment by chitoyuu** [comment]
Thanks for the initiative!

> But I think it should be included at the start as well since users start following instructions before reading the troubleshooting.

Very good point. I would perhaps do it as a blockquote "alert" like the ["bit of context" one](https://godot-rust.github.io/book/gdnative/export/android.html#a-bit-of-context), right at the top, given how likely a user might run into this problem on the first attempt.

As this is expected to be a temporary issue, it would be good to note the time of writing and include a link to the upstream issue for context.
